### ISSUE TITLE
Initial position bottom right instead of center position

### ISSUE THREAD

**Issue by shalinisubramani** [hyper-designed/box_transform#17]
Is this possbile the box displayed bottom right in the entire screen.

**Actual Result:**
<img width="945" alt="image" src="https://github.com/hyper-designed/box_transform/assets/6822777/77a33be1-3770-446e-b7f8-15138735a075">

**Expecting Result**
<img width="1470" alt="image" src="https://github.com/hyper-designed/box_transform/assets/6822777/bd5d3812-2ea3-4988-b5b9-0b308986bef6">

**Comment by SaadArdati** [comment]
Hey there @shalinisubramani, you can absolutely have the initial position be at the bottom right. You have complete control over the rectangle's state.

Please provide more code if you need further assistance.

**Comment by SaadArdati** [comment]
Closed. Please open a new issue with a more in-depth explanation if you still require assistance.
