### ISSUE TITLE
Feature： transform-box in scroll area

### ISSUE THREAD

**Issue by dhx-worker** [hyper-designed/box_transform#18]
### I wish I used this box for scrollable areas, unfortunately I see that currently a Stack layout is required outside the box. This layout doesn't seem to support scrolling, right?

**Comment by BirjuVachhani** [comment]
Hey @dhx-worker, Would mind explaining your use-case in a bit more detail? What kind of scrolling are you talking about?

Yes, a stack layout is required currently since you can resize the box in any direction.

**Comment by SaadArdati** [comment]
Closed. Please open a new issue with a more in-depth use-case or explanation.
