### ISSUE TITLE
Support for dragging outside of parent Stack widget

### ISSUE THREAD

**Issue by matthewrice345** [hyper-designed/box_transform#22]
**Is your feature request related to a problem? Please describe.**
Is there any way to support drag, resize, etc where the transform box is partially outside of the parent `Stack` widget? It appears that the `TransformableBox` returns a `Positioned` widget which means that a solution like `defer_pointer` wouldn't work. Wrapping the Positioned with anything other than a Stack can cause errors. 

**Describe the solution you'd like**
The ability to drag a `TransformableBox` when it is partially or completely outside of the parent Stack widget. Currently the `Stack.hitText` function will not recognize the gestures.

**Describe alternatives you've considered**
I tried to fork the library (great library BTW) and use a builder to allow me from an app to wrap the direct child of the Positioned widget in TransformableBox with a DeferPointer. This creates some other errors with the widget being out of context. 

**Additional context**
I'm aware I can place restrictions on allowing the TransformableBox to be allowed to go outside the stack. For my use case it is important that it does and I'm just looking for any possible solution you may have in mind.

Thanks!

**Comment by SaadArdati** [comment]
@matthewrice345 There is no way to lay out a widget in a freeform space in Flutter without using Positioned/Stack Widgets or using a custom RenderObject.

I would try to restructure your widget trees such that the problematic Stack is always sized to the size of the screen and then rendering any "out of bounds" areas using a CustomClipper or CustomPainter or using any other method. It's fairly straight forward to do it that way instead.

Alternatively, if you really are in a position where no alternative is possible, especially considering you're relying on a third-party package to do some obtuse operation, you can extend or implement our TransformableBox widget with your own custom implementation that does what you need it to do, which is not terribly complicated. It's a fairly straight forward widget.

In the end, `flutter_box_transform` is a complete wrapper for `box_transform`. The entire system is intentionally flexible for odd cases like yours :)

**Comment by matthewrice345** [comment]
@SaadArdati Thanks for the response. I think I found a work around for my situation. Appreciate the suggestions
