### ISSUE TITLE
resize bug

### ISSUE THREAD

**Issue by ixuiyaxa** [hyper-designed/box_transform#26]
Hello.
I am Japanese and I am posting through a translator.

I am currently developing an application on IOS and I have found two events that I believe are bugs.
First, when I try to move it while resizing it, it minimizes when I release my finger. (Is the behavior also suspicious when operating with multiple fingers?)
In this case, if the resizeModeResolver is set to ResizeMode.scale, it will spread out in a square regardless of its initial size when you try to expand it.

In the following video, here (https://boxtransform-demo.hyperdesigned.dev/) I repeatedly touch the resize area, then move it with another finger and release my finger.

https://github.com/hyper-designed/box_transform/assets/172169405/a7919a23-302b-42ae-9f1c-cd50303e2107

Second, when the resize is reduced to less than minWidth,minHeight, it returns to the size at which it started to resize. (This occurs when resizeModeResolver is ResizeMode.scale.)

I would appreciate any workarounds for these problems.

The code we are producing is handled by our business, so we do not want to paste any videos or sources.

If you need something, please let us know and we will create it separately.
Thank you in advance.

-Original text before translation below-
こんにちは。
私は日本人なので翻訳機を介して投稿させていただきます。

現在IOSでアプリケーションを開発しているのですが、バグだと考えられる事象を二つ発見しました。
一点目に、リサイズさせながら移動させようとすると指を離した際に最小化されてしまいます。(複数の指で操作しているときの挙動も怪しい？)
このとき、resizeModeResolverがResizeMode.scaleになっていると広げてみても初期サイズにかかわらず正方形で広がっていってしまいます。

下記の動画では、ここで（https://boxtransform-demo.hyperdesigned.dev/）リサイズ部分に触れてからもう一つの指で移動させ指を離すのを繰り返しています。

二点目に、minWidth,minHeight以下までリサイズされると、リサイズし始めた大きさまで戻ってしまいます。（これは、resizeModeResolverがResizeMode.scaleの時に発生します。）

これらの問題の回避策がありましたら教えてほしいです。

制作中のコードは業務で扱っているものなので、動画やソースは貼り付けたくありません。

何か必要でしたら、別途作成いたしますのでお伝えください。
よろしくお願いします。

**Comment by ixuiyaxa** [comment]
Is this issue currently being addressed?

**Comment by SaadArdati** [comment]
Yes but it will take time as we are very busy. If you believe you can fix it quickly, feel free to make a PR request.

**Comment by SaadArdati** [comment]
Fixed in release 0.4.3

**Comment by ixuiyaxa** [comment]
Thank you very much.
I have confirmed that the first problem has been resolved, but has the second problem been resolved?
In my environment, if the image is resized to less than minWidth,minHeight, it returns to the size at which it started resizing. (when resizeModeResolver is set to ResizeMode.scale)

**Comment by SaadArdati** [comment]
@ixuiyaxa I am not sure what you mean by that. Scaling is not resetting back to its original size when it hits its minimum for me.

Can you please file a separate issue with detailed steps-by-step instructions to reproduce?
